### ISSUE TITLE
BUG right click action on a non-rotatable block changes player displayname color

### ISSUE THREAD

**Issue by heathfx** [JoelGodOfwar/RotationalWrench#5]
on 1.17.1 with no other plugins and a clean world. Right c;licking on a non-rotatable block results in the player's display name being turned grey (observed in the tablist).

The rotation functionality works correctly with rotatable blocks and when the tool successfully rotates a block no change is observed in the player's display name.

## To Reproduce
start a fresh world with default configs running the latest 1.17.1 release of airplane (paper fork) and this plugin. Right click on dirt. stone, etc. with an empty hand and observe the player's displayname turning grey in the tab list.

**Comment by heathfx** [comment]
This behavior is also observed with PaperMC build 788 (latest) on 1.16.5 with 100% default configs and randomly generated world

**Comment by JoelGodOfwar** [comment]
Confirmed, this was left behind test code for another plugin. This will be fixed in 1.14_1.0.5 which should be released before you read this.
